import './globals.css';
import { Roboto } from 'next/font/google';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Blogging App',
  description: 'Generated by Viktor Drok',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ roboto.className }>{ children }</body>
    </html>
  );
}
