// import dynamic from 'next/dynamic';
export const dynamic = 'force-dynamic';
// const Header = dynamic(() => import("./components/Header"), { ssr: false });

import './globals.css';
import { Roboto } from 'next/font/google';
import Header from './components/Header';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Blogging App',
  description: 'Generated by Viktor Drok',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ roboto.className }>
        <Header />
        { children }
      </body>
    </html>
  );
}
